- name: Print variable from inventory
  hosts: local
  connection: local
  tasks: 
  - name: print the variable 
    ansible.builtin.debug:
      msg: "My name is {{name}}, my address is {{locality, city, pin}}"
    