- name: Install packages
  hosts: web
  become: true
  tasks:
  - name: Install packages
    ansible.builtin.package:
      name: "{{ item }}"
      state: present
    loop:
    - git
    - python3
    - mysql
    - gcc
    - zip

  - name: Remove packages
    ansible.builtin.package:
      name: "{{ item.name }}"
      state: "{{ item.state}}"
    loop:
    - { name: 'gcc', state: 'absent' }
    - { name: 'zip', state: 'absent' }