- name: printing variables from commandline
  hosts: localhost
  connection: localhost
  tasks:
  - name: print the variable
    debug:
      msg: "My name is {{name}} and my address is {{locality, city, pin}}"