- name: printing the datatypes
  hosts: local
  connection: local
  vars:
    name: "Anjan"
    age: 27
    height: 5.9
    skills:
    - linux
    - shell
    - ansible
    - aws
    active: true
    address:
      locality: gandhinagar
      city: "bangalore"
      pin: 560076
    empty_value: null
    tasks:
    - name: printing my information
      debug:
        msg: "my name is {{name}}, age: {{age}}, height: {{height}}, my skills are {{skills}} and my address is {{address}} and iam {{active}}"