- name: printing the value if it's greater than 10 or not
  hosts: local
  connection: local
  vars_prompt:
  - name: value
    prompt: "please enter your value"
    private: false
  tasks:
  - name: printing the value
    ansible.builtin.debug:
      msg: "your value: {{value}} is greater than 10"
    when: value > 10