- name: configuring frontend server
  hosts: frontend
  become: true
  tasks:
  - name: Install nginx
    package:
      name: nginx
      state: present

  - name: enable and start nginx service
    ansible.builtin.service:
      name: nginx
      state: started
      enabled: true

  - name: remove default content that web-browser is serving
    ansible.builtin.file:
      path: /usr/share/nginx/html
      state: absent

  - name: create new html directory
    ansible.builtin.file:
      path: /usr/share/nginx/html
      state: directory

  - name: download frontend data
    ansible.builtin.get_url:
      url: https://expense-builds.s3.us-east-1.amazonaws.com/expense-frontend-v2.zip
      dest: /tmp/frontend.zip

  - name: extract the downloaded data
    ansible.builtin.unarchive:
      src: /tmp/frontend.zip
      dest: /usr/share/nginx/html
      remote_src: yes

  - name: copy expense config
    ansible.builtin.copy:
      src: expense.conf
      dest: /etc/nginx/default.d/expense.conf

  - name: restart nginx service
    ansible.builtin.service:
      name: nginx
      state: restarted
  